#pragma once

#include "Common.h"

namespace Quartz
{
	enum ButtonAction
	{
		/* Indiviual Actions */
		BUTTON_ACTION_NONE		= 0x00,
		BUTTON_ACTION_UP		= 0x01,
		BUTTON_ACTION_DOWN		= 0x02,
		BUTTON_ACTION_PRESSED	= 0x04,
		BUTTON_ACTION_RELEASED	= 0x08,
		BUTTON_ACTION_REPEAT	= 0x10,

		/* Combo Actions */
		BUTTON_ACTION_ANY		= (BUTTON_ACTION_UP | BUTTON_ACTION_DOWN | BUTTON_ACTION_PRESSED | BUTTON_ACTION_RELEASED | BUTTON_ACTION_REPEAT),
		BUTTON_ACTION_ANY_UP	= (BUTTON_ACTION_UP | BUTTON_ACTION_RELEASED),
		BUTTON_ACTION_ANY_DOWN	= (BUTTON_ACTION_DOWN | BUTTON_ACTION_PRESSED | BUTTON_ACTION_REPEAT)
	};

	enum MouseWheelAction
	{
		/* Indiviual Actions */
		MOUSE_WHEEL_ACTION_NONE		= 0x00,
		MOUSE_WHEEL_ACTION_UP		= 0x01,
		MOUSE_WHEEL_ACTION_DOWN		= 0x02,

		/* Combo Actions */
		MOUSE_WHEEL_ACTION_ANY		= (MOUSE_WHEEL_ACTION_UP | MOUSE_WHEEL_ACTION_DOWN)
	};

	typedef Flags8 ButtonActions;
	typedef Flags8 MouseWheelActions;
}