#pragma once

#include "Common.h"

namespace Quartz
{
	enum InputAction
	{
		/* Indiviual Actions */
		INPUT_ACTION_NONE		= 0x00,
		INPUT_ACTION_UP			= 0x01,
		INPUT_ACTION_DOWN		= 0x02,
		INPUT_ACTION_PRESSED	= 0x04,
		INPUT_ACTION_RELEASED	= 0x08,
		INPUT_ACTION_REPEAT		= 0x10,

		/* Axis Actions */
		INPUT_ACTION_ACTIVE		= 0x20,

		/* Combo Actions */
		INPUT_ACTION_ANY		= (INPUT_ACTION_UP | INPUT_ACTION_DOWN | INPUT_ACTION_PRESSED | INPUT_ACTION_RELEASED | INPUT_ACTION_REPEAT),
		INPUT_ACTION_ANY_UP		= (INPUT_ACTION_UP | INPUT_ACTION_RELEASED),
		INPUT_ACTION_ANY_DOWN	= (INPUT_ACTION_DOWN | INPUT_ACTION_PRESSED | INPUT_ACTION_REPEAT)
	};

	enum MouseWheelAction
	{
		/* Indiviual Actions */
		MOUSE_WHEEL_ACTION_NONE		= 0x00,
		MOUSE_WHEEL_ACTION_UP		= 0x01,
		MOUSE_WHEEL_ACTION_DOWN		= 0x02,

		/* Combo Actions */
		MOUSE_WHEEL_ACTION_ANY		= (MOUSE_WHEEL_ACTION_NONE | MOUSE_WHEEL_ACTION_UP | MOUSE_WHEEL_ACTION_DOWN)
	};

	typedef Flags8 InputActions;
	typedef Flags8 MouseWheelActions;
}